// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Test.Models
{
    public partial class Member
    {
        public Member()
        {
            OwnCollections = new HashSet<OwnCollection>();
            Photos = new HashSet<Photo>();
        }

        public int Id { get; set; }
        public string Name { get; set; }
        public string Account { get; set; }
        public string Password { get; set; }

        public virtual ICollection<OwnCollection> OwnCollections { get; set; }
        public virtual ICollection<Photo> Photos { get; set; }
    }
}