// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Test.Models
{
    public partial class Photo
    {
        public Photo()
        {
            OwnCollections = new HashSet<OwnCollection>();
        }

        public int Id { get; set; }
        public string Source { get; set; }
        public int MemberId { get; set; }

        public virtual Member Member { get; set; }
        public virtual ICollection<OwnCollection> OwnCollections { get; set; }
    }
}